#############################################################################
# Makefile for building: infinitecoin-qts
# Generated by qmake (2.01a) (Qt 4.8.7) on: ?? ?? 20 15:42:47 2019
# Project:  bitcoin-qt-win.pro
# Template: app
# Command: c:/qt_4.8.7_static/bin/qmake.exe RELEASE=1 USE_UPNP=0 USE_QRCODE=1 USE_IPV6=0 -o Makefile bitcoin-qt-win.pro
#############################################################################

first: release
install: release-install
uninstall: release-uninstall
MAKEFILE      = Makefile
QMAKE         = c:/qt_4.8.7_static/bin/qmake.exe
DEL_FILE      = rm
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp
COPY_FILE     = $(COPY)
COPY_DIR      = cp -r
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = mv
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		release \
		debug

release: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_default: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-make_first: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release first
release-all: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_default: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-make_first: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug first
debug-all: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: bitcoin-qt-win.pro  ../Qt_4.8.7_static/mkspecs/win32-g++/qmake.conf ../Qt_4.8.7_static/mkspecs/features/device_config.prf \
		../Qt_4.8.7_static/mkspecs/qconfig.pri \
		../Qt_4.8.7_static/mkspecs/features/qt_functions.prf \
		../Qt_4.8.7_static/mkspecs/features/qt_config.prf \
		../Qt_4.8.7_static/mkspecs/features/exclusive_builds.prf \
		../Qt_4.8.7_static/mkspecs/features/default_pre.prf \
		../Qt_4.8.7_static/mkspecs/features/win32/default_pre.prf \
		../Qt_4.8.7_static/mkspecs/features/release.prf \
		../Qt_4.8.7_static/mkspecs/features/debug_and_release.prf \
		../Qt_4.8.7_static/mkspecs/features/default_post.prf \
		../Qt_4.8.7_static/mkspecs/features/win32/default_post.prf \
		../Qt_4.8.7_static/mkspecs/features/staticlib.prf \
		../Qt_4.8.7_static/mkspecs/features/static.prf \
		../Qt_4.8.7_static/mkspecs/features/win32/thread.prf \
		../Qt_4.8.7_static/mkspecs/features/win32/rtti.prf \
		../Qt_4.8.7_static/mkspecs/features/win32/exceptions.prf \
		../Qt_4.8.7_static/mkspecs/features/win32/stl.prf \
		../Qt_4.8.7_static/mkspecs/features/warn_on.prf \
		../Qt_4.8.7_static/mkspecs/features/qt.prf \
		../Qt_4.8.7_static/mkspecs/features/moc.prf \
		../Qt_4.8.7_static/mkspecs/features/win32/windows.prf \
		../Qt_4.8.7_static/mkspecs/features/resources.prf \
		../Qt_4.8.7_static/mkspecs/features/uic.prf \
		../Qt_4.8.7_static/mkspecs/features/yacc.prf \
		../Qt_4.8.7_static/mkspecs/features/lex.prf \
		c:/Qt_4.8.7_static/lib/qtmain.prl \
		c:/Qt_4.8.7_static/lib/QtGui.prl \
		c:/Qt_4.8.7_static/lib/QtNetwork.prl \
		c:/Qt_4.8.7_static/lib/QtCore.prl
	$(QMAKE) RELEASE=1 USE_UPNP=0 USE_QRCODE=1 USE_IPV6=0 -o Makefile bitcoin-qt-win.pro
../Qt_4.8.7_static/mkspecs/features/device_config.prf:
../Qt_4.8.7_static/mkspecs/qconfig.pri:
../Qt_4.8.7_static/mkspecs/features/qt_functions.prf:
../Qt_4.8.7_static/mkspecs/features/qt_config.prf:
../Qt_4.8.7_static/mkspecs/features/exclusive_builds.prf:
../Qt_4.8.7_static/mkspecs/features/default_pre.prf:
../Qt_4.8.7_static/mkspecs/features/win32/default_pre.prf:
../Qt_4.8.7_static/mkspecs/features/release.prf:
../Qt_4.8.7_static/mkspecs/features/debug_and_release.prf:
../Qt_4.8.7_static/mkspecs/features/default_post.prf:
../Qt_4.8.7_static/mkspecs/features/win32/default_post.prf:
../Qt_4.8.7_static/mkspecs/features/staticlib.prf:
../Qt_4.8.7_static/mkspecs/features/static.prf:
../Qt_4.8.7_static/mkspecs/features/win32/thread.prf:
../Qt_4.8.7_static/mkspecs/features/win32/rtti.prf:
../Qt_4.8.7_static/mkspecs/features/win32/exceptions.prf:
../Qt_4.8.7_static/mkspecs/features/win32/stl.prf:
../Qt_4.8.7_static/mkspecs/features/warn_on.prf:
../Qt_4.8.7_static/mkspecs/features/qt.prf:
../Qt_4.8.7_static/mkspecs/features/moc.prf:
../Qt_4.8.7_static/mkspecs/features/win32/windows.prf:
../Qt_4.8.7_static/mkspecs/features/resources.prf:
../Qt_4.8.7_static/mkspecs/features/uic.prf:
../Qt_4.8.7_static/mkspecs/features/yacc.prf:
../Qt_4.8.7_static/mkspecs/features/lex.prf:
c:\Qt_4.8.7_static\lib\qtmain.prl:
c:\Qt_4.8.7_static\lib\QtGui.prl:
c:\Qt_4.8.7_static\lib\QtNetwork.prl:
c:\Qt_4.8.7_static\lib\QtCore.prl:
qmake: qmake_all FORCE
	@$(QMAKE) RELEASE=1 USE_UPNP=0 USE_QRCODE=1 USE_IPV6=0 -o Makefile bitcoin-qt-win.pro

qmake_all: FORCE

make_default: release-make_default debug-make_default FORCE
make_first: release-make_first debug-make_first FORCE
all: release-all debug-all FORCE
clean: release-clean debug-clean FORCE
distclean: release-distclean debug-distclean FORCE
	-$(DEL_FILE) Makefile

check: first

release-mocclean: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
